name: Build and deploy to Azure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      #OpenArabicMusicDB
      - name: Building OpenArabicMusicDB domain
        run: |
          npm install
          npm run build
          npm link
        working-directory: ./domain

      - name: Building OpenArabicMusicDB builder
        run: |
          npm link openarabicmusicdb-domain
          npm install
          npm run compile
          npm run build-db
        working-directory: ./builder

      #Deploy to Azure
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Deploy to Azure
        run: |
          az storage blob upload --file ./dist/db.json --blob-url https://arabicmusicdbstorage.blob.core.windows.net/dbstorage/db.json --auth-mode login --overwrite
          az webapp restart --resource-group arabicmusicencyclopedia --name arabicmusicencyclopedia-backend
          az logout
        working-directory: ./builder
