name: Publish package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish-domain:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Check package version vs registry
        id: version_check
        uses: dupy-ts/check-package-version@main
        with:
          path: ./domain
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Echo versions
        run: |
            echo "Committed version: ${{ steps.version_check.outputs.committed-version }}"
            echo "Retrieved version: ${{ steps.version_check.outputs.retrieved-version }}"
            echo "Has been published: ${{ steps.version_check.outputs.is-published }}"

      - name: Publish package
        if: steps.version_check.outputs.is-new-version == 'true' || steps.version_check.outputs.is-published == 'false'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npm run build
          npm publish
        working-directory: ./domain